# Generated by Django 4.0.2 on 2022-02-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlibrary',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='userlibrary',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userwallet',
            old_name='user_id',
            new_name='user',
        ),
    ]
