# Generated by Django 4.0.2 on 2022-02-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='catetory',
            new_name='category',
        ),
    ]
