# Generated by Django 4.0.2 on 2022-02-18 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_catetory_book_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=200)),
                ('public_date', models.DateTimeField()),
                ('isbn', models.CharField(max_length=15)),
                ('intro', models.CharField(max_length=600)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_detail', to='books.book')),
            ],
            options={
                'db_table': 'book_details',
            },
        ),
    ]
