# Generated by Django 4.0.2 on 2022-02-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_url',
            field=models.URLField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
