# Generated by Django 4.0.2 on 2022-02-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file_url',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
