# Generated by Django 4.0.2 on 2022-02-21 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_category_alter_book_file_url_book_category'),
        ('reviews', '0002_rename_book_id_review_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_book', to='books.book'),
        ),
    ]
