# Generated by Django 4.0.2 on 2022-02-21 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_link_url_remove_order_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bookoption_id',
            new_name='bookoption',
        ),
    ]
